### ISSUE TITLE
Incorrect insets.bottom value on the devices with Android 5.x.x and hardware buttons

### ISSUE THREAD

**Issue by DanielMarkiel** [th3rdwave/react-native-safe-area-context#39] opened 2020-01-14 10:08 UTC
The package returns incorrect `insets.bottom` value on the devices with Android 5.x.x and hardware buttons. E.g. Samsung S4.

Code example:
```js
import { useSafeArea } from 'react-native-safe-area-context';

...

const Component = () => {
  const insets = useSafeArea();
  console.log(insets.bottom); // prints 48 - it should be 0

  ...
}
```

**Comment by luancurti** [comment] 2020-01-20 19:16
Same problem using `version: 0.6.1` tested on Android `5.1.1`

**Comment by tomsotte** [comment] 2020-01-23 09:52
Same problem using version: `0.6.2` tested on Android `4.4` (API level 19) device `Nexus 5 emulator`.

**Comment by muhamad-rizki** [comment] 2020-04-01 02:08
hello @janicduplessis , any news about this issue ? what about this PR #43  ?

**Comment by schieck0** [comment] 2020-04-23 17:55
Same problem here. Asus Zenfone 2 Laser. Android 5.0.2 with hardware buttons.
![WhatsApp Image 2020-04-23 at 14 53 30](https://user-images.githubusercontent.com/9256271/80132610-52caa680-8572-11ea-92f7-b0f9d8e8cfca.jpeg)

**Comment by tsdmrfth** [comment] 2020-05-01 20:48
Hello. I have same problem. Any progress?

**Comment by luancurti** [comment] 2020-05-02 01:36
This problem is fixed in the version `0.7.3` in think this [commit](https://github.com/th3rdwave/react-native-safe-area-context/commit/f0228a906801d2585460aa77e5bfcebdb8f770fc) fixed. The problem with the wrong top is causing this side effect

**Comment by tsdmrfth** [comment] 2020-05-02 10:14
@luancurti The problem is about wrong _bottom_ values actually

**Comment by luancurti** [comment] 2020-05-02 17:56
@tsdmrfth Yes, I quoted the wrong top fixed the wrong bottom you see this commit? You tested with the 0.7.3 version?

**Comment by tsdmrfth** [comment] 2020-05-02 19:20
@luancurti Yes. 
<img width="413" alt="Screen Shot 2020-05-02 at 22 19 55" src="https://user-images.githubusercontent.com/27639087/80874066-0e9e7b00-8cc3-11ea-8c1c-bf96b8ca54b7.png">

**Comment by janicduplessis** [comment] 2020-05-04 21:17
This should be fixed in v1.0.0-beta.2.

**Closed by janicduplessis** 2020-05-04 21:17 UTC

**Comment by schieck0** [comment] 2020-05-13 11:50
Tested version 1.0.0 on Asus Zenfone 2 and Samsung J1 Mini:
Incorrect insets bottom PERSISTS. Somebody else?

**Comment by ammarahm-ed** [comment] 2022-07-25 10:26
Still having this issue with soft bottom buttons on android

**Comment by parth-koshta** [comment] 2023-01-30 10:36
Anybody found any fix for this? 
I'm seeing this on Samsung devices.
