### ISSUE TITLE
Issue with react navigation bottom tab - tabs not clickable android

### ISSUE THREAD

**Issue by Jalson1982** [th3rdwave/react-native-safe-area-context#141] opened 2020-09-01 20:19 UTC
Hello. In a project with react-native-safe-area-context version 0.7.3 all works but with the latest version I have a big issue on android devices. The clickable area of bottom tabs is reduced to the top only ( you can take a look at the image ). I am not sure what I can do to fix this ( reverting back is not an option as we use a lot of the latest options provided by react-native-safe-area-context ). Any advice pls pls...

![image](https://user-images.githubusercontent.com/35011526/91901909-29005980-eca1-11ea-9f99-536d000043cf.png)

**Comment by Jalson1982** [comment] 2020-09-02 12:23
Further investigation shows that bottom bar is hidden by soft android navigation... any advice?

**Comment by leonidas-1** [comment] 2020-11-13 00:44
Removing status bar translucent still not working for me, 
any ideas or solution? 
Thanks!

**Comment by simongoot** [comment] 2021-09-07 05:13
@Jalson1982 we found the problem and managed to resolve this issue yesterday. It was caused by ModalProvider from react-native-modalfy package ( https://github.com/colorfy-software/react-native-modalfy )

The problem was resolved in the latest update of the package and most likely their backdrop heigh issue from using window instead of screen dimensions for calculating the size of it.

**Comment by jacobp100** [comment] 2023-01-19 16:07
This is for v3 of the library, and we're on v4. Please re-open a new issue if you're still facing issues

**Closed by jacobp100** 2023-01-19 16:07 UTC
