### ISSUE TITLE
IOS devices without notches get stucked

### ISSUE THREAD

**Issue by felippepuhle** [th3rdwave/react-native-safe-area-context#14] opened 2019-10-03 23:55 UTC
Hey folks, first of all thanks for this library, it's amazing!

This week I moved on from `react-native-safe-area-view` to `react-native-safe-area-context` and I noticed my app wasn't running in some devices without notches.
Unfortunately I had n log and I have no idea what's happening (it's not a crash itself, my app just get stucked on splash screen).

Earlier this afternoon I started to debug and found that's related to this lib.
I just removed `<SafeAreaProvider></SafeAreaProvider>` and it started to work again (obviously I couldn't get the insets from the context anymore lol)

Any thoughts? Apparently `SafeAreaProvider` isn't rendering children somehow.

I'd be glad to help.

Thanks!

**Comment by janicduplessis** [comment] 2019-10-06 17:26
Hey @felippepuhle!

The `SafeAreaProvider` renders nothing until it receives a value from native for the safeAreaInsets. It is possible that something causes that even to never be received. Do you know what on what device / iOS version this happened?

**Comment by usrbowe** [comment] 2019-10-07 09:34
I have the same issue.

I tested `iOS12.4` with `iPhone SE, iPhone 7` all got stuck. 
It doesn't render anything past the `SafeAreaProvider` component.

@janicduplessis

**Comment by felippepuhle** [comment] 2019-10-07 12:17
Hey guys, good morning.

I noticed it was happening last week, after my app was denied several times by AppStore.
I was able to reproduce on many simulators like iPhone 6, iPhone 8, etc (all devices without notches).

In my case, I was calling `useSafeArea` just after the app started.
Is there anywhere I can get any log and try to help you guys?

Thanks!

**Comment by usrbowe** [comment] 2019-10-08 02:23
Just quick findings. Basically the issue lies here: 
https://github.com/th3rdwave/react-native-safe-area-context/blob/2d73e6f245782c58ab7f270e2fbff6ecdb2d6d2b/ios/SafeAreaView/RNCSafeAreaView.m#L78
The `self.onInsetsChange` will never get called, so it always renders `null`, since `insets` will be `null`
https://github.com/th3rdwave/react-native-safe-area-context/blob/2d73e6f245782c58ab7f270e2fbff6ecdb2d6d2b/src/index.tsx#L26-L30

**Comment by janicduplessis** [comment] 2019-10-08 18:28
I see what can happen. I added a fix to make sure insets are sent initially 9b23dea23cd8c3372a10176a3a134b678b7ed515. I also made sure we call the method in layoutSubviews too even if insets are supported in case it doesn't get called by ios for some reason. Since we check if insets are equal it won't cause extra events to be sent.

Released in 0.4.1, could you verify that it fixes the issue?

**Comment by felippepuhle** [comment] 2019-10-08 19:14
Sure, I'll test it ASAP.
Thanks

**Comment by usrbowe** [comment] 2019-10-09 03:30
@janicduplessis @felippepuhle I can confirm it works, tested on `iPhone 8 (iOS13)`.

**Comment by janicduplessis** [comment] 2019-10-09 06:45
Awesome! Thanks

**Closed by janicduplessis** 2019-10-09 06:45 UTC

**Comment by Mahlyjan** [comment] 2020-05-31 10:06
Hi, I am getting a problem with:

Unable to resolve "./SafeAreaContext" from "node_modules\react-native-safe-area-context\src\index.tsx"

If anyone knows how to fix this, please help.
It comes up when we do a:

**export default function App() {
  return <Navigator />;
}**
