### ISSUE TITLE
[Android] Task :react-native-safe-area-context:compileReleaseKotlin FAILED

### ISSUE THREAD

**Issue by bulkinav** [th3rdwave/react-native-safe-area-context#481] opened 2024-03-14 09:03 UTC
"react-native": "0.73.6"
"react-native-safe-area-context": "4.9.0"

IS_NEW_ARCHITECTURE_ENABLED = TRUE
bridgelessEnabled = FALSE

Android Studio 2023.2.1

buildToolsVersion = "34.0.0"
minSdkVersion = 23 // Android 6.0 and above
compileSdkVersion = 34 // Android 14 (gives access to new APIs)
targetSdkVersion = 33 // Android 13
ndkVersion = "25.1.8937393"
kotlinVersion = "1.8.22"

---

Hello,

When I'm trying to build the my project (release or begug - it does not matter) with IS_NEW_ARCHITECTURE_ENABLED = TRUE, the following error occurs:

```
> Task :react-native-safe-area-context:compileReleaseKotlin FAILED
e: file:/app-react/node_modules/react-native-safe-area-context/android/src/fabric/java/com/th3rdwave/safeareacontext/InsetsChangeEvent.kt:7:16 Redeclaration: InsetsChangeEvent
e: file:/app-react/node_modules/react-native-safe-area-context/android/src/fabric/java/com/th3rdwave/safeareacontext/UIManagerHelperCompat.kt:8:1 Conflicting overloads: public fun getReactContext(view: View): ReactContext defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt, public fun getReactContext(view: View): ReactContext defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt
e: file:/app-react/node_modules/react-native-safe-area-context/android/src/fabric/java/com/th3rdwave/safeareacontext/UIManagerHelperCompat.kt:12:1 Conflicting overloads: public fun getSurfaceId(context: Context): Int defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt, public fun getSurfaceId(context: Context): Int defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt
e: file:/app-react/node_modules/react-native-safe-area-context/android/src/paper/java/com/th3rdwave/safeareacontext/InsetsChangeEvent.kt:9:16 Redeclaration: InsetsChangeEvent
e: file:/app-react/node_modules/react-native-safe-area-context/android/src/paper/java/com/th3rdwave/safeareacontext/UIManagerHelperCompat.kt:9:1 Conflicting overloads: public fun getReactContext(view: View): ReactContext defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt, public fun getReactContext(view: View): ReactContext defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt
e: file:/app-react/node_modules/react-native-safe-area-context/android/src/paper/java/com/th3rdwave/safeareacontext/UIManagerHelperCompat.kt:18:1 Conflicting overloads: public fun getSurfaceId(context: Context): Int defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt, public fun getSurfaceId(context: Context): Int defined in com.th3rdwave.safeareacontext in file UIManagerHelperCompat.kt
```

**Comment by 404-html** [comment] 2024-03-16 12:49
I am experiencing the same on RN `0.74.0-rc.3`

**Comment by jacobp100** [comment] 2024-03-16 14:54
The main issue is for the new arch. We’ll happily take fixes for issues you find, but because the new arch is still considered alpha/beta, support is patchy

For the second issue, I think someone has done fixes for the RC versions, but you’re best to wait until it’s fully shipped

If you find a root cause or a minimal repro, please do open a new issue or PR. I’ll close this because it won’t get actioned, and just keep the active issues a bit cleaner

**Closed by jacobp100** 2024-03-16 14:54 UTC
