### ISSUE TITLE
Build failed: 'react/renderer/components/view/ViewProps.h' file not found

### ISSUE THREAD

**Issue by Iamivan1996** [th3rdwave/react-native-safe-area-context#539] opened 2024-10-24 06:20 UTC
### **Issue**
I am going to upgrade my personal React Native project to version 0.76.0 to conduct a health check and see if most of the common libraries are compatible with the latest version. Found out there is an issue when building the Android App
___
### **Error Message**
In file included from node_modules/react-native-safe-area-context/common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewState.h:3:
node_modules/react-native-safe-area-context/android/src/main/jni/../../../build/generated/source/codegen/jni/react/renderer/components/safeareacontext/Props.h:12:10: fatal error: 'react/renderer/components/view/ViewProps.h' file not found
#include <react/renderer/components/view/ViewProps.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         
         
In file included from node_modules/react-native-safe-area-context/common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewShadowNode.cpp:1:
In file included from node_modules/react-native-safe-area-context/common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewShadowNode.h:4:
node_modules/react-native-safe-area-context/android/src/main/jni/../../../build/generated/source/codegen/jni/react/renderer/components/safeareacontext/EventEmitters.h:12:10: fatal error: 'react/renderer/components/view/ViewEventEmitter.h' file not found
#include <react/renderer/components/view/ViewEventEmitter.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
___
### **Dependencies**
"react-native": "0.76.0",
"react-native-safe-area-context": "^4.11.1"

**Comment by Rohit3523** [comment] 2024-10-24 07:23
Getting the same error

**Comment by abdullah-tsx** [comment] 2024-10-24 07:33
+1

**Comment by Rohit3523** [comment] 2024-10-24 07:52
They have an active PR, https://github.com/th3rdwave/react-native-safe-area-context/pull/538

I hope it get merged asap

**Comment by gautamsamyak** [comment] 2024-10-24 09:53
Getting the same error.

**Comment by iM-GeeKy** [comment] 2024-10-24 10:51
Here is a patch using `patch-package` as a temporary workaround.

```
diff --git a/node_modules/react-native-safe-area-context/android/src/main/jni/CMakeLists.txt b/node_modules/react-native-safe-area-context/android/src/main/jni/CMakeLists.txt
index 4ee1c8f..9a76ec3 100644
--- a/node_modules/react-native-safe-area-context/android/src/main/jni/CMakeLists.txt
+++ b/node_modules/react-native-safe-area-context/android/src/main/jni/CMakeLists.txt
@@ -37,25 +37,37 @@ target_include_directories(
   ${LIB_ANDROID_GENERATED_COMPONENTS_DIR}
 )
 
-target_link_libraries(
-  ${LIB_TARGET_NAME}
-  fbjni
-  folly_runtime
-  glog
-  jsi
-  react_codegen_rncore
-  react_debug
-  react_nativemodule_core
-  react_render_core
-  react_render_debug
-  react_render_graphics
-  react_render_mapbuffer
-  react_render_componentregistry
-  react_utils
-  rrc_view
-  turbomodulejsijni
-  yoga
-)
+# https://github.com/react-native-community/discussions-and-proposals/discussions/816
+# This if-then-else can be removed once this library does not support version below 0.76
+if (REACTNATIVE_MERGED_SO)
+  target_link_libraries(
+          ${LIB_TARGET_NAME}
+          fbjni
+          jsi
+          reactnative
+  )
+else()
+  target_link_libraries(
+          ${LIB_TARGET_NAME}
+          fbjni
+          folly_runtime
+          glog
+          jsi
+          react_codegen_rncore
+          react_debug
+          react_nativemodule_core
+          react_render_core
+          react_render_debug
+          react_render_graphics
+          react_render_mapbuffer
+          react_render_componentregistry
+          react_utils
+          rrc_view
+          turbomodulejsijni
+          yoga
+  )
+endif()
+
 
 target_compile_options(
   ${LIB_TARGET_NAME}
```

**Comment by akuul** [comment] 2024-10-24 11:42
You can use old architecture for the time being until PR is merged.

**Comment by Rohit3523** [comment] 2024-10-24 17:32
> Which version should I use? i tried 4.11.1 got this error. tried 4.10.0 as well any idea anyone?

Use the latest version and create a patch for it using patch-package library 

https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282

Use this code in the patch file

**Comment by sujathasperi2022** [comment] 2024-10-24 18:18
> > Which version should I use? i tried 4.11.1 got this error. tried 4.10.0 as well any idea anyone?
> 
> Use the latest version and create a patch for it using patch-package library
> 
> [#539 (comment)](https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282)
> 
> Use this code in the patch file

which file ViewProps.h?

**Comment by craiganderson-iotv** [comment] 2024-10-24 22:50
@sujathasperi2022 

Create a `patches` folder alongside your `node_modules` like so:
```
MyAwesomeApp
- node_modules
- src
- android
- ios
- patches
```

Inside the `patches` folder, create a file called `react-native-safe-area-context+4.11.1.patch` and copy/paste the code from [#539 (comment)](https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282)

**Comment by hasithmeth** [comment] 2024-10-24 23:48
> @sujathasperi2022
> 
> Create a `patches` folder alongside your `node_modules` like so:
> 
> ```
> MyAwesomeApp
> - node_modules
> - src
> - android
> - ios
> - patches
> ```
> 
> Inside the `patches` folder, create a file called `react-native-safe-area-context+4.11.1.patch` and copy/paste the code from [#539 (comment)](https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282)

Thank you so much!

**Comment by usemain** [comment] 2024-10-25 02:25
> @sujathasperi2022
> 
> 在您的旁边创建一个文件夹，如下所示：`patches``node_modules`
> 
> ```
> MyAwesomeApp
> - node_modules
> - src
> - android
> - ios
> - patches
> ```
> 
> 在文件夹内，创建一个名为 [#539 （comment）](https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282) 的文件并复制/粘贴代码`patches``react-native-safe-area-context+4.11.1.patch`

Still a failure!

**Comment by Iamivan1996** [comment] 2024-10-25 02:52
@usemain The temporary fix works for me, and I was able to build Android successfully. I also found that there are a couple of libraries that have the same error. Are you using react-native-screens or react-native-gesture-handler?

For react-native-screens, you may need to update the version to [4.0.0-beta.13](https://github.com/software-mansion/react-native-screens/releases/tag/4.0.0-beta.13)
Ref : https://github.com/software-mansion/react-native-screens/pull/2415

And for the react-native-gesture-handler, update the version to [2.20.2](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.20.2) 
Ref : https://github.com/software-mansion/react-native-gesture-handler/pull/3109

**Comment by erie-e9** [comment] 2024-10-25 07:08
Hi guys, facing issues with initial RN project,

Packages:

"react": "18.3.1",
"react-i18next": "^15.1.0",
"react-native": "0.76.0",
"@react-navigation/native": "^6.1.18",
"@react-navigation/stack": "^6.4.1",

**Comment by erie-e9** [comment] 2024-10-25 07:49
Hi guys, facing issues with initial RN project, I also followed @craiganderson-iotv advice,

Error: Execution failed for task ':app:checkDebugDuplicateClasses'.

Packages:
"react": "18.3.1",
"react-native": "0.76.0",
"@react-navigation/native": "^6.1.18",
"@react-navigation/stack": "^6.4.1",
"react-native-safe-area-context": "^4.11.1",
"react-native-screens": "4.0.0-beta.13",
"react-native-gesture-handler": "2.20.2"

Steps:
- [ ] Init new project
- [ ] Install packages
- [ ] patch react-native-safe-area-context, following [#539 (comment)](https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282) 
- [ ] Sync gradle, clean and remove android/build, android/app/build and android/app/.cxx folders
- [ ] Run rebuild

Output: Two errors

1.
<img width="1056" alt="Captura de pantalla 2024-10-25 a la(s) 1 38 55 a m" src="https://github.com/user-attachments/assets/dcb11b49-8d46-47dc-bf76-a3cff74ffc0b">
2.
<img width="1056" alt="Captura de pantalla 2024-10-25 a la(s) 1 39 17 a m" src="https://github.com/user-attachments/assets/ba067f1e-d789-4144-9a59-871bf1890274">

**Comment by Rohit3523** [comment] 2024-10-25 08:49
@erie-e9 Try upgrading `react-native-gesture-handler` and `react-native-screen` package

**Comment by DhvaniChavdaAseum** [comment] 2024-10-25 10:52
getting same error

**Comment by laurensk** [comment] 2024-10-25 13:37
+1

**Comment by akuul** [comment] 2024-10-25 14:05
FIY `react-native-screens 3.35.0` has 0.76 support so no need to update to `-beta` release

**Comment by tuan0919** [comment] 2024-10-25 14:34
> @sujathasperi2022
> 
> Create a `patches` folder alongside your `node_modules` like so:
> 
> ```
> MyAwesomeApp
> - node_modules
> - src
> - android
> - ios
> - patches
> ```
> 
> Inside the `patches` folder, create a file called `react-native-safe-area-context+4.11.1.patch` and copy/paste the code from [#539 (comment)](https://github.com/th3rdwave/react-native-safe-area-context/issues/539#issuecomment-2434941282)
> 
> Then, run `npx patch-package` to apply the patch It may be necessary to delete the `android/build` and `android/app/.cxx` folders

this didn't work for me, still encounter this error after patch:
```
/node_modules/react-native-safe-area-context/android/src/main/jni/../../../build/generated/source/codegen/jni/react/renderer/components/safeareacontext/EventEmitters.h:12:10: fatal error: 'react/renderer/components/view/ViewEventEmitter.h' file not found
```

**Comment by erie-e9** [comment] 2024-10-25 19:00
> @erie-e9 Try upgrading `react-native-gesture-handler` and `react-native-screen` package
> 
> For react-native-screens you will have to use version `4.0.0-beta.13`

I am already the using latest versions, in my first comment I added the used packages versions.

**Comment by Jakub-Plan-d-k** [comment] 2024-10-25 19:26
+1

**Comment by janicduplessis** [comment] 2024-10-25 22:25
Duplicate of https://github.com/th3rdwave/react-native-safe-area-context/issues/541, should be fixed now.

**Closed by janicduplessis** 2024-10-25 22:25 UTC

**Comment by sujathasperi2022** [comment] 2024-10-26 05:37
@craiganderson-iotv Unfortunaltely the patch didnt work. But thank you for the information and effort. 
Withe the latest 4.12.0 of react-native safe area context app is building at my end.
the below is my config
`   "react": "18.3.1",
    "react-native": "0.76.0",
     "react-native-safe-area-context": "^4.12.0",
    "react-native-screens": "^3.35.0",
    "react-native-gesture-handler": "^2.20.2"`

**Comment by Rohit3523** [comment] 2024-10-26 06:41
@sujathasperi2022 just share the error log, multiple libraries are throwing same error at the time 

As I can see the culprit is react-native-screen because you are using stable version which is giving same error as this package, just do `npm install react-native-screens@4.0.0-beta.13`

Also don't forget to share the error

**Comment by jienigui1117ss** [comment] 2024-10-28 11:57
the problem is     "react-native-safe-area-context": "4.12.0", you must upgrade this to "4.12.0" and it worked.
this is my env     ext {
        buildToolsVersion = "35.0.0"
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"
    } 
good luck everyone.

**Comment by jienigui1117ss** [comment] 2024-10-28 11:57
the problem is "react-native-safe-area-context": "4.12.0", you must upgrade this to "4.12.0" and it worked.
this is my env ext {
buildToolsVersion = "35.0.0"
minSdkVersion = 24
compileSdkVersion = 35
targetSdkVersion = 34
ndkVersion = "26.1.10909125"
kotlinVersion = "1.9.24"
}

**Comment by Rohit3523** [comment] 2024-10-28 12:04
> the problem is "react-native-safe-area-context": "4.12.0", you must upgrade this to "4.12.0" and it worked. this is my env ext { buildToolsVersion = "35.0.0" minSdkVersion = 24 compileSdkVersion = 35 targetSdkVersion = 34 ndkVersion = "26.1.10909125" kotlinVersion = "1.9.24" }

????

**Comment by georgi2005atanasov** [comment] 2025-01-13 11:44
I have the same error. Did anyone solve it?

**Comment by zjkuang** [comment] 2025-01-16 20:26
I have the same error with
"react-native": "0.76.6"
"react-native-safe-area-context": "5.1.0"
