### ISSUE TITLE
SafeAreaView adds extra padding with headerMode='none' in react-navigation nested navigator

### ISSUE THREAD

**Issue by IngyuTae** [th3rdwave/react-native-safe-area-context#143] opened 2020-09-13 15:00 UTC
It works with react-native's SafeAreaView as expected but I'm not sure it is on purpose.

![SafeAreaView](https://user-images.githubusercontent.com/24571455/93021582-5bee0a00-f61e-11ea-8343-377d1ab05fff.png)

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';

import {Text} from 'react-native';
import {SafeAreaProvider, SafeAreaView} from 'react-native-safe-area-context';

import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();

const HomeScreen = () => {
  return (
    <SafeAreaView
      style={{flex: 1, backgroundColor: 'yellow', justifyContent: 'flex-end'}}>
      <Text>justifyContent: 'flex-end'</Text>
    </SafeAreaView>
  );
};

const BottomTab = () => {
  return (
    <Tab.Navigator tabBarOptions={{tabStyle: {backgroundColor: 'red'}}}>
      <Tab.Screen name="Home" component={HomeScreen} />
    </Tab.Navigator>
  );
};

const HomeStack = () => {
  return (
    // if headerMode = "none", extra padding is added at the bottom
    <Stack.Navigator headerMode="none">
      <Stack.Screen name="BottomTab" component={BottomTab} />
    </Stack.Navigator>
  );
};

const App = () => {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <HomeStack />
      </NavigationContainer>
    </SafeAreaProvider>
  );
};

export default App;
```

```json
{
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1"
  }
}
```

**Comment by Reizar** [comment] 2020-10-02 02:22
I have the same issue. It adds a small amount of blank space above the tab bar. And so my child views can't be full height which looks jarring.

Would be great if anyone knows a fix for this.

**Comment by jneterer** [comment] 2020-10-09 20:27
I am having the same issue. It is adding space both above and below when using SafeAreaView when header mode is none.

![Screen Shot 2020-10-09 at 4 26 32 PM](https://user-images.githubusercontent.com/32587255/95628521-33ee9c80-0a4c-11eb-8fcd-d55a5d883e8b.png)

**Comment by ajaykumar97** [comment] 2020-10-22 07:08
This seems to be the solution:

https://github.com/th3rdwave/react-native-safe-area-context/issues/107#issuecomment-652616230

**Comment by jacobp100** [comment] 2020-10-30 22:26
You gotta nest every single route component in a `SafeAreaProvider`.

E.g.

```js
const HomeScreen = () => {
  return (
    <SafeAreaProvider style={{flex:1}}>
      <SafeAreaView
        style={{flex: 1, backgroundColor: 'yellow', justifyContent: 'flex-end'}}>
        <Text>justifyContent: 'flex-end'</Text>
      </SafeAreaView>
    </SafeAreaProvider>
  );
};
```

**Comment by jneterer** [comment] 2020-10-30 22:43
@jacobp100 thanks for your response, however that is not the issue. The issue is when using two SafeAreaView's, one for the top and bottom of the screen.

@ajaykumar97 I believe I tried that and it did not work, but I will give it a go again.

**Comment by jacobp100** [comment] 2020-10-30 22:57
@jneterer The SafeAreaProvider will set the safe area for all child SafeAreaViews. If the top SafeAreaProvider does not extend into the bottom safe area (or bottom SAP doesn't extend into the top SA), it will not set bottom safe area insets on any of the child SafeAreaViews.

**Comment by IngyuTae** [comment] 2020-10-30 23:43
here's my workaround using custom hook

```typescript
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { useNavigation } from '@react-navigation/native';

import { nestedNavigationProp, stackNavigationProp } from '../app/rootNavigation';

const useSafeArea = () => {
  const navigation = useNavigation<stackNavigationProp | nestedNavigationProp>();
  const insets = useSafeAreaInsets();

  const navState = navigation.dangerouslyGetParent()?.dangerouslyGetState();

  return { ...insets, bottom: navState?.type === 'tab' ? 0 : insets.bottom };
};

export default useSafeArea;
```

**Closed** 2023-01-19 16:09 UTC
