### ISSUE TITLE
ANR: com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getRootWindowInsetsCompatR

### ISSUE THREAD

**Issue by devoren** [th3rdwave/react-native-safe-area-context#437] opened 2023-10-04 14:17 UTC
ANR from google play: 
```
"main" tid=1 Runnable
  at android.view.WindowInsets.getInsets (WindowInsets.java:217)
  at android.view.WindowInsets.getInsets (WindowInsets.java:343)
  at com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getRootWindowInsetsCompatR (SafeAreaUtils.kt:15)
  at com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getRootWindowInsetsCompat (SafeAreaUtils.kt:55)
  at com.th3rdwave.safeareacontext.SafeAreaUtilsKt.getSafeAreaInsets (SafeAreaUtils.kt:67)
  at com.th3rdwave.safeareacontext.SafeAreaProvider.maybeUpdateInsets (SafeAreaProvider.kt:18)
  at com.th3rdwave.safeareacontext.SafeAreaProvider.onPreDraw (SafeAreaProvider.kt:39)
  at android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:1112)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:4197)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2919)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:10491)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1108)
  at android.view.Choreographer.doCallbacks (Choreographer.java:866)
  at android.view.Choreographer.doFrame (Choreographer.java:797)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1092)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8669)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```
```
"react-native-safe-area-context": "^4.6.3"
"react-native": "0.71.8"
```
Devices: 
`samsung a21s (Galaxy A21s) - Android 12 (SDK 31)`

**Comment by jacobp100** [comment] 2023-10-04 15:07
This is happening in Android land - https://developer.android.com/reference/android/view/WindowInsets

There's really nothing we can go off here. If you manage to get ahold of a device you can reliably reproduce the error, and do some investigation, we'd love to hear and we can work together towards a fix

However, I'll have to close this issue because it's not really actionable. Hope this makes sense

**Closed by jacobp100** 2023-10-04 15:07 UTC
