### ISSUE TITLE
Unresolved reference: NativeSafeAreaContextSpec with `newArchEnabled=true` 

### ISSUE THREAD

**Issue by davidhu2000** [th3rdwave/react-native-safe-area-context#323] opened 2022-10-19 19:55 UTC
```
> Task :react-native-safe-area-context:compileDebugKotlin FAILED
e: <path>/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt: (11, 5): Unresolved reference: NativeSafeAreaContextSpec
e: <path>/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt: (12, 3): 'getName' overrides nothing
e: <path>/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt: (16, 10): 'getTypedExportedConstants' overrides nothing
e: <path>/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt: (21, 21): Unresolved reference: reactApplicationContext
e: <path>/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt: (17, 37): Type mismatch: inferred type is SafeAreaContextModule but NativeModule? was expected
e: <path>/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt: (23, 55): Type mismatch: inferred type is Class<SafeAreaContextModule> but Class<out NativeModule?> was expected
```

seeing this error during `yarn android` 

suspect that the error is due to the fact that 

`NativeSafeAreaContextSpec` is in `src/paper`

https://github.com/th3rdwave/react-native-safe-area-context/blob/8f93c44f14a5ea4fd398457848abb75809d66ecd/android/src/paper/java/com/th3rdwave/safeareacontext/NativeSafeAreaContextSpec.java#L28

and build.gradle do not include the paper folder if newArch is enabled 

https://github.com/th3rdwave/react-native-safe-area-context/blob/8f93c44f14a5ea4fd398457848abb75809d66ecd/android/build.gradle#L71-L80

```
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 478.30 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /private/var/folders/4_/4ngnwlm12y5cghx9sqftw3fw0000gn/T/xfs-92193bd3/node
    Yarn: 3.2.3 - /private/var/folders/4_/4ngnwlm12y5cghx9sqftw3fw0000gn/T/xfs-92193bd3/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/davidhu/.rvm/gems/ruby-3.1.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

package.json versions

```json
    "@react-native-community/art": "1.2.0",
    "@react-native-community/async-storage": "1.12.1",
    "@react-navigation/native": "6.0.13",
    "@react-navigation/native-stack": "6.9.1",
    "@tanstack/react-query": "4.9.0",
    "react": "18.2.0",
    "react-native": "0.70.3",
    "react-native-gradle-plugin": "0.71.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "3.18.2",
    "react-native-svg": "13.2.0",
    "react-native-vector-icons": "9.2.0",
```

**Comment by davidhu2000** [comment] 2022-10-19 20:05
another note is i was seeing errors like 

```
fatal error: 'react/renderer/components/safeareacontext/Props.h' file not found
```

but using the suggestion [here](https://github.com/software-mansion/react-native-screens/issues/1420#issuecomment-1156169274) 

that issue was fixed by removing `react-native-codegen` from the devDeps

**Comment by arichayo** [comment] 2022-10-20 21:25
So did removing codegen solve your issue? I don't have codegen in my package.json

**Comment by davidhu2000** [comment] 2022-10-20 21:28
> So did removing codegen solve your issue? I don't have codegen in my package.json

no it did not. it only resolved 

```
fatal error: 'react/renderer/components/safeareacontext/Props.h' file not found
```

but I still get this error

```
Unresolved reference: NativeSafeAreaContextSpec
```

**Comment by arichayo** [comment] 2022-10-20 21:30
Been having the same issue driving me nuts the past few days with this older project I'm upgrading

**Comment by TravellerOnTheRun** [comment] 2022-11-01 11:45
Is there any workaround/solution for this? I'm having the same issue

**Comment by evelant** [comment] 2022-11-03 00:05
I'm hitting this now too, anybody find a workaround?

**Comment by evelant** [comment] 2022-11-03 19:09
Possibly related, I see this in the gradle output

```
[RUN_GRADLEW] > Task :react-native-safe-area-context:generateCodegenSchemaFromJavaScript
[RUN_GRADLEW] No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds modules.
```

I think codegen is supposed to be creating the missing files but isn't doing it for some reason.

**Comment by evelant** [comment] 2022-11-03 20:32
@davidhu2000 @TravellerOnTheRun I finally got it to build. I had to add the following to my `devDependencies`, if you use different versions the build fails.

```
"react-native-codegen": "^0.70.6",
"react-native-gradle-plugin": "^0.70.3"
```

I also set a number of env variables, I'm not sure if all of them are necessary however, my build command looked like:

```
USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 ANDROID_NDK_HOME=/Users/myuser/dev/Android/sdk/ndk ORG_GRADLE_PROJECT_newArchEnabled=true ORG_GRADLE_PARALLEL=false ORG_GRADLE_PROJECT_disableMultipleInstancesCheck=true pnpm build-app
```

**Comment by davidhu2000** [comment] 2022-11-07 22:20
@evelant thank you! That helped us to get a build. we didn't have to add the flags, but locking devDep to those versions helped.

**Comment by evelant** [comment] 2022-11-07 22:35
@davidhu2000 Now that I have it building I'm running into a different issue, are you seeing this one? https://github.com/expo/expo/issues/19866

**Comment by davidhu2000** [comment] 2022-11-07 22:42
that's not something i've seen. we are also not using expo.

**Comment by LoserAntbear** [comment] 2022-11-10 13:40
> @davidhu2000 @TravellerOnTheRun I finally got it to build. I had to add the following to my `devDependencies`, if you use different versions the build fails.
> 
> ```
> "react-native-codegen": "^0.70.6",
> "react-native-gradle-plugin": "^0.70.3"
> ```
> 
> I also set a number of env variables, I'm not sure if all of them are necessary however, my build command looked like:
> 
> ```
> USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 ANDROID_NDK_HOME=/Users/myuser/dev/Android/sdk/ndk ORG_GRADLE_PROJECT_newArchEnabled=true ORG_GRADLE_PARALLEL=false ORG_GRADLE_PROJECT_disableMultipleInstancesCheck=true pnpm build-app
> ```

Could you, please, kindly provide the way  you find that out? It can be useful for similar cases in other libraries.

**Comment by LoserAntbear** [comment] 2022-11-11 22:54
> we actually ended up having to disable the new arch. While it build fine on emulator, when we created the prod builds, the app crashes on launch due to some SVg issues
> 
> ```
> E  Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager.
>    
>    This error is located at:
>        in RNSVGPath
>        in Path
>        in RNSVGMask
>        in Mask
>        in RNSVGGroup
>        in G
>        in RNSVGSvgView
>        in Svg
>        in SvgComponent
>        in RCTView
>        in Unknown
>        in NativeWind.View
>        in Unknown
>        in RCTView
>        in Unknown
>        in NativeWind.View
> ```

Could you check if all the peer dependencies are installed? I had a similar case and it was about missing peer dependencies in installed packages.

Regarding the mentioned topic. I also encountered the issue:
`fatal error: 'react/renderer/components/safeareacontext/Props.h' file not found`

We are using monorepo structure. I was able to resolve it completely by:
1. Removing all the node modules folders manually
2. Re-checking possible conflicting dependencies (e.g. packageA and packageB having same dependencies with different versions).
4. Confirmed peer-dependencies installed and of latest versions.
3. Checked setup of every core library for working with new architecture. For example, `react-native-reanimated` supports Fabric only starting with version `3.0.0-rc1` - but it is not in go-live yet.
4.  In `projectName/ios/.xcode.env` file set environment variables, providing new architecture flags:
```
export NODE_BINARY=$(command -v node)
export USE_FABRIC=true
export RCT_NEW_ARCH_ENABLED=true
```
5. Cleared build cache in XCode (cmd+shift+K).
6. Started metro with cache reset.

Did it for me.

**Comment by aprilmintacpineda** [comment] 2022-12-10 12:10
Currently going through this error, been a few hours, really hard to fix when there's not much information about it

No solution above worked for me, mine looks like related to a library I'm using which I can't tell which one

`my-project/react-native/ios/build/generated/ios/react/renderer/components/safeareacontext/ShadowNodes.cpp:11:10 'react/renderer/components/safeareacontext/ShadowNodes.h' file not found`

```c

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <react/renderer/components/safeareacontext/ShadowNodes.h>

namespace facebook {
namespace react {

extern const char RNCSafeAreaProviderComponentName[] = "RNCSafeAreaProvider";

} // namespace react
} // namespace facebook
```

![image](https://user-images.githubusercontent.com/21032419/206854357-976b0d0f-67f5-47c8-998d-48f620da8b0a.png)

**Comment by jacobp100** [comment] 2023-03-16 11:16
Is this fixed? Can I close it?

**Comment by tex0l** [comment] 2023-06-19 17:17
I'm experiencing the same issue, I'm currently trying the workaround suggested above, but they are definitely too hacky to close the issue imho.

**Comment by jacobp100** [comment] 2023-07-11 10:17
Closing because RN is on 0.72 and we probably won't backport new arch fixes for older versions

**Closed by jacobp100** 2023-07-11 10:17 UTC
Labels: help wanted, Platform: Android, New arch

**Comment by huynhtastic** [comment] 2023-07-28 22:56
@jacobp100 i'm currently researching if our team is able to migrate to the new arch. Does that mean we should upgrade to `0.72` before trying to migrate to new arch with this lib installed?

**Comment by jacobp100** [comment] 2023-07-29 09:44
Yes you should be on the latest version. I’d recommend you don’t switch to the new arch unless your team has the ability to write and fix native code, because most packages don’t fully support the new arch yet

**Comment by Yuniac** [comment] 2024-01-29 09:47
Same issue here: `'react/renderer/components/safeareacontext/Props.h' file not found` and I have given up on trying to fix it so I will just not use the new arch for now
